# Site settings
title: Macroscopicentric
description: > # this means to ignore newlines until "baseurl:"
  Hi, I'm Rachel, a recovering Pythonista who now primarily works in the wild
  wild west land that is Ruby.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: magpieohmy
github_username:  macroscopicentric

# Build settings
markdown: kramdown
