title: Macroscopicentric
description: >
  Hi, I'm Rachel, an infrastructure engineer with a soft spot for wordplay and modern sci fi.

url: http://macroscopicentric.net
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/
author: magpieohmy

gems:
  - jekyll-feed
  - jekyll-paginate

markdown: kramdown
highlighter: rouge
paginate: 5

navigation:
  - title: Home
    url: /index.html
  - title: About
    url: /about
  - title: RSS
    url: /feed.xml

social:
  github: macroscopicentric
  twitter: magpieohmy

google_analytics: "UA-141707062-1"
