title: Macroscopicentric
description: >
  Hi, I'm Rachel, a recovering Pythonista who now primarily works in the wild
  wild west land that is Ruby.

url: http://macroscopicentric.github.com/personal_site
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about

social:
   github: macroscopicentric
   twitter: magpieohmy

google_analytics: ""
