title: Macroscopicentric
description: >
  Hi, I'm Rachel, a recovering Pythonista who now primarily works in the wild
  wild west land that is Ruby.

url: http://macroscopicentric.github.com/personal_site
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: pygments
paginate: 5

social:
   github: macroscopicentric
   twitter: magpieohmy

google_analytics: ""
